<?php

declare(strict_types=1);

/**
 * Configuration
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Echo Server API
 *
 * Echo Server API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: team@openapitools.org
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client;

/**
 * PaginationInterface Class Doc Comment
 *
 * For a better response behavior as well as maintain the best security level, All retrieving API endpoints use a mechanism to retrieve data in chunks called pagination. Pagination working by return only a specific number of records in each response, and through passing the page number you can navigate the different pages.
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
interface PaginationInterface
{
    /**
     * The number of returned results
     */
    public function getCount(): int;

    /**
     * The total number of all results
     */
    public function getTotal(): int;

    /**
     * The number of results per page
     */
    public function getPerPage(): int;

    /**
     * The number of current page
     */
    public function getCurrentPage(): int;

    /**
     * The number of next page
     */
    public function getNextPage(): ?int;

    /**
     * The number of total pages
     */
    public function getTotalPages(): int;

    /**
     * If there are more pages.
     */
    public function hasMore(): bool;

    /**
     * Array of links to next and previous pages
     *
     * @return array{next?: string, previous?: string}
     */
    public function getLinks(): array;
}
