<?php
/**
 * AuthApiInterface
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Echo Server API
 *
 * Echo Server API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: team@openapitools.org
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Promise\PromiseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;

/**
 * AuthApi Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
interface AuthApiInterface
{
    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'testAuthHttpBasic' => [
            'application/json',
        ],
        'testAuthHttpBearer' => [
            'application/json',
        ],
    ];

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void;

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int;

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration;

    /**
     * Operation testAuthHttpBasic
     *
     * To test HTTP basic authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBasic'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return string
     */
    public function testAuthHttpBasic(
        string $contentType = self::contentTypes['testAuthHttpBasic'][0]
    ): string;

    /**
     * Operation testAuthHttpBasicWithHttpInfo
     *
     * To test HTTP basic authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBasic'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function testAuthHttpBasicWithHttpInfo(
        string $contentType = self::contentTypes['testAuthHttpBasic'][0]
    ): array;

    /**
     * Operation testAuthHttpBasicAsync
     *
     * To test HTTP basic authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBasic'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function testAuthHttpBasicAsync(
        string $contentType = self::contentTypes['testAuthHttpBasic'][0]
    ): PromiseInterface;

    /**
     * Operation testAuthHttpBasicAsyncWithHttpInfo
     *
     * To test HTTP basic authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBasic'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function testAuthHttpBasicAsyncWithHttpInfo(
        string $contentType = self::contentTypes['testAuthHttpBasic'][0]
    ): PromiseInterface;

    /**
     * Create request for operation 'testAuthHttpBasic'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBasic'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function testAuthHttpBasicRequest(
        string $contentType = self::contentTypes['testAuthHttpBasic'][0]
    ): Request;
    /**
     * Operation testAuthHttpBearer
     *
     * To test HTTP bearer authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBearer'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return string
     */
    public function testAuthHttpBearer(
        string $contentType = self::contentTypes['testAuthHttpBearer'][0]
    ): string;

    /**
     * Operation testAuthHttpBearerWithHttpInfo
     *
     * To test HTTP bearer authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBearer'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function testAuthHttpBearerWithHttpInfo(
        string $contentType = self::contentTypes['testAuthHttpBearer'][0]
    ): array;

    /**
     * Operation testAuthHttpBearerAsync
     *
     * To test HTTP bearer authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBearer'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function testAuthHttpBearerAsync(
        string $contentType = self::contentTypes['testAuthHttpBearer'][0]
    ): PromiseInterface;

    /**
     * Operation testAuthHttpBearerAsyncWithHttpInfo
     *
     * To test HTTP bearer authentication
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBearer'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function testAuthHttpBearerAsyncWithHttpInfo(
        string $contentType = self::contentTypes['testAuthHttpBearer'][0]
    ): PromiseInterface;

    /**
     * Create request for operation 'testAuthHttpBearer'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['testAuthHttpBearer'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function testAuthHttpBearerRequest(
        string $contentType = self::contentTypes['testAuthHttpBearer'][0]
    ): Request;
}
