<?php

declare(strict_types=1);

/**
 * ClientBuilder
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\Api\AnotherFakeApi;
use OpenAPI\Client\Api\DefaultApi;
use OpenAPI\Client\Api\FakeApi;
use OpenAPI\Client\Api\FakeClassnameTags123Api;
use OpenAPI\Client\Api\PetApi;
use OpenAPI\Client\Api\StoreApi;
use OpenAPI\Client\Api\UserApi;

/**
 * ClientBuilder Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @property-read AnotherFakeApi $anotherFake
 * @property-read DefaultApi $default
 * @property-read FakeApi $fake
 * @property-read FakeClassnameTags123Api $fakeClassnameTags123
 * @property-read PetApi $pet
 * @property-read StoreApi $store
 * @property-read UserApi $user
 */
class ClientBuilder
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Initiates new client builder with OAuth access token.
     * @link https://docs.salla.dev/docs/merchant/2fa0d7aca2def-authorization
     *
     * @param string $accessToken
     * @throws \InvalidArgumentException
     * @return ClientBuilder
     */
    public static function createWithAccessToken(
        string $accessToken
    ): static {
        if (empty($accessToken)) {
            throw new \InvalidArgumentException('Access token cannot be empty');
        }

        $config = new Configuration();
        $config->setAccessToken($accessToken);

        return new static(null, $config);
    }

    /**
     * @link https://docs.salla.dev/doc-421118
     */
    public static function createWithOAuth(
        string $clientId,
        string $clientSecret,
        string $redirectUri,
        ?string $accessToken = null,
        ?string $refreshToken = null
    ): static {
        $config = new Configuration();
        if (empty($accessToken) === false) {
            $config->setAccessToken($accessToken);
        }
        if (empty($refreshToken) === false) {
            $config->setRefreshToken($refreshToken);
        }
        $config->setOAuthProvider(new \Salla\OAuth2\Client\Provider\Salla([
            'clientId'     => $clientId,
            'clientSecret' => $clientSecret,
            'redirectUri'  => $redirectUri,
        ]));

        return new static(null, $config);
    }

    /**
     * {@inheritDoc}
     */
    public function __get(string $name)
    {
        switch ($name) {
            case 'anotherFake':
                return new AnotherFakeApi($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            case 'default':
                return new DefaultApi($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            case 'fake':
                return new FakeApi($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            case 'fakeClassnameTags123':
                return new FakeClassnameTags123Api($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            case 'pet':
                return new PetApi($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            case 'store':
                return new StoreApi($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            case 'user':
                return new UserApi($this->client, $this->config, $this->headerSelector, $this->hostIndex);
            default:
                throw new \InvalidArgumentException(\sprintf('Unknown property "%s"', $name));
        }
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }
}
